### ISSUE TITLE
Any candidate function for flush_tlb_mm_range in arm64?

### ISSUE THREAD

**Issue by JoeyJiao** [AFLplusplus/AFL-Snapshot-LKM#12]
# cat /proc/kallsyms |grep flush|grep tlb
ffffff921225ed68 T tlb_flush_mmu
ffffff921225ef98 T tlb_table_flush

A closer one, but it's inlined in kernel.
static inline void flush_tlb_range(struct vm_area_struct *vma, unsigned long start, unsigned long end)

**Comment by andreafioraldi** [comment]
the module does not works on arm64 atm, even the page fault hook is x86/64 only

**Comment by andreafioraldi** [comment]
Atm snapshot mode is for LLVM mode only, we assume that you have sources and can recompile on x86

**Comment by vanhauser-thc** [comment]
@JoeyJiao if you want to port the lkm to arm64 we would be happy though :)
