### ISSUE TITLE
kallsyms_lookup_name unexported in newer kernel

### ISSUE THREAD

**Issue by mothran** [AFLplusplus/AFL-Snapshot-LKM#6]
While attempting to build the module on a newer kernel I hit build error:
ERROR: modpost: "kallsyms_lookup_name" [src/afl_snapshot.ko] undefined!

Turns out recent patches to the kernel have unexported the kallsyms_lookup_name symbol so it can't be easily used in out-of-tree builds [1][2].  It's possible I might have missed something in my setup though.

Kernel version: 5.7.7-arch1-1

References:
[1] https://lkml.org/lkml/2020/2/21/1269
[2] https://lwn.net/Articles/813350/

**Comment by andreafioraldi** [comment]
Maybe fixed in https://github.com/AFLplusplus/AFL-Snapshot-LKM/commit/0620b076889bb10bbcacba2d83c0d8dfe67de301
Can you try to checkout that commit?
